package VIEW;

import CONFIG_DB.ConnMySQL;
import CONTROLLER.CarroController;
import MODELS.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;

public class Alocar extends javax.swing.JFrame {
    Cliente cliente;
    ArrayList<Carro> carros;
    int index,dias;
    Date Dinicial,Dfinal;
    
    public Alocar(Cliente cliente) {
        this.cliente = cliente;
        System.out.println(index);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextLista = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextModelo = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextFabricante = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextCor = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextAno = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextPreco = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextDInicial = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TextDFinal = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TextBusca = new javax.swing.JTextPane();
        BtnAlugar = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        TextPrecoTotal = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnProcurar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alocar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TextLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TextLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TextLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextListaMouseClicked(evt);
            }
        });
        TextLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                TextListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(TextLista);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Selecione um modelo");

        TextModelo.setEditable(false);
        TextModelo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(TextModelo);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Modelo");

        TextFabricante.setEditable(false);
        TextFabricante.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jScrollPane3.setViewportView(TextFabricante);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Fabricante");

        TextCor.setEditable(false);
        TextCor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jScrollPane4.setViewportView(TextCor);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Cor");

        TextAno.setEditable(false);
        TextAno.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jScrollPane5.setViewportView(TextAno);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Ano");

        TextPreco.setEditable(false);
        TextPreco.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jScrollPane6.setViewportView(TextPreco);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Preço (Diário) R$");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Data inicial (dd/mm/yyyy)");

        TextDInicial.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TextDInicial.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TextDInicialInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        TextDInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDInicialKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(TextDInicial);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Data Final (dd/mm/yyyy)");

        TextDFinal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TextDFinal.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TextDFinalInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        TextDFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDFinalKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(TextDFinal);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Procurar por");

        TextBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextBuscaKeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(TextBusca);

        BtnAlugar.setBackground(new java.awt.Color(0, 200, 0));
        BtnAlugar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnAlugar.setText("Alugar");
        BtnAlugar.setToolTipText("");
        BtnAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlugarActionPerformed(evt);
            }
        });

        TextPrecoTotal.setEditable(false);
        TextPrecoTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jScrollPane11.setViewportView(TextPrecoTotal);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Preço Total R$");

        ErrorLabel.setForeground(new java.awt.Color(251, 0, 0));

        BtnProcurar.setText("Procurar");
        BtnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcurarActionPerformed(evt);
            }
        });

        BtnGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton1.setText("Modelo");

        BtnGroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton2.setText("Fabricante");

        BtnGroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton3.setText("Cor");

        BtnGroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton4.setText("Ano");

        BtnGroup.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButton5.setText("Preço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(BtnAlugar)
                        .addGap(292, 292, 292))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(BtnProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5)
                                .addGap(14, 14, 14)
                                .addComponent(BtnProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnAlugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlugarActionPerformed
        if(!TextDInicial.getText().equals("") && !TextDFinal.getText().equals("")){
            if(TextDInicial.getText().contains("-")){
            }else{
                if(TextDInicial.getText().contains("/")){
                }else{
                    ErrorLabel.setText("Modelo inválido de data em Data Inicial!");
                    return;
                }
            }

            if(TextDFinal.getText().contains("-")){
            }else{
                if(TextDFinal.getText().contains("/")){
                }else{
                    ErrorLabel.setText("Modelo inválido de data em Data Final!");
                    return;
                }
            }
            ErrorLabel.setText("");
        }else{
            ErrorLabel.setText("Preencha os campos de Data!");
            return;
        }
        
        if(TextPrecoTotal.getText().equals("")){
            ErrorLabel.setText("O preço final não foi ajustado. Tente novamente.");
            return;
        }
        
        Connection conexao = ConnMySQL.conexao();  
        String sql = "INSERT INTO Aluguel (id_cliente,id_carro,preco,data_inicial,data_final)" +
                     "VALUES (?,?,?,?,?)";
        try{
            SimpleDateFormat sdfbarra = new SimpleDateFormat("dd/MM/yyyy");
            
            PreparedStatement statement = conexao.prepareStatement(sql);
            statement.setInt(1, cliente.getId());
            statement.setInt(2, carros.get(index).getId());
            statement.setInt(3, carros.get(index).getAluguel()*dias);
            statement.setString(4, sdfbarra.format(Dinicial));
            statement.setString(5, sdfbarra.format(Dfinal));

            int linhas = statement.executeUpdate();
            if(linhas>0){
                System.out.println("\nCarro alugado com Sucesso!\n");
            }else{
                System.err.println("\nCarro não alugado! Tente novamente!\n");
            }
        }catch(SQLException throwables){
            throwables.printStackTrace();
        }
        MessageWindow mensagem = new MessageWindow("Carro alugado com sucesso!");
        mensagem.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BtnAlugarActionPerformed

    private void TextListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextListaMouseClicked
        
    }//GEN-LAST:event_TextListaMouseClicked

    private void TextListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_TextListaValueChanged
        index = TextLista.getSelectedIndex();
        System.out.println("Index Selected: " + index);
        String s = (String) TextLista.getSelectedValue();
        System.out.println("Value Selected: " + s);
        
        carros.get(index);
        
        TextModelo.setText(carros.get(index).getModelo());
        TextFabricante.setText(carros.get(index).getFabricante());
        TextCor.setText(carros.get(index).getCor());
        TextAno.setText("" + carros.get(index).getAno());
        TextPreco.setText("" + carros.get(index).getAluguel());
        
        TextPrecoTotal.setText("");
    }//GEN-LAST:event_TextListaValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<Carro> aux = new ArrayList();
        CarroController.getAll(aux);
        ArrayList<Carro> carros = CarroController.OrdenaCarros(aux);
        this.carros = carros;
        DefaultListModel model = new DefaultListModel(); 
        this.TextLista.setModel(model);         
        for(int i = 0; i < carros.size(); i++){
            model.addElement(carros.get(i).getModelo());
        }
    }//GEN-LAST:event_formWindowOpened

    private void TextDInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDInicialKeyTyped
        dias = 1;
        try{
            Date temp;     
            Calendar data_inicial = Calendar.getInstance();
            Calendar data_final = Calendar.getInstance();
            
            SimpleDateFormat sdftraco = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat sdfbarra = new SimpleDateFormat("dd/MM/yyyy");

            if(TextDInicial.getText().contains("-")){
                temp = sdftraco.parse(TextDInicial.getText());
                Dinicial = temp;
                data_inicial.setTime(temp);
            }else{
                if(TextDInicial.getText().contains("/")){
                    temp = sdfbarra.parse(TextDInicial.getText());
                    Dinicial = temp;
                    data_inicial.setTime(temp);
                }else{
                    return;
                }
            }
            
            if(TextDFinal.getText().contains("-")){
                temp = sdftraco.parse(TextDFinal.getText());
                Dfinal = temp;
                data_final.setTime(temp);
            }else{            
                if(TextDFinal.getText().contains("/")){
                    temp = sdfbarra.parse(TextDFinal.getText());
                    Dfinal = temp;
                    data_inicial.setTime(temp);
                }else{
                    return;
                }
            }
            
            int MILLIS_IN_DAY = 86400000;

            data_inicial.set(Calendar.MILLISECOND, 0);
            data_inicial.set(Calendar.SECOND, 0);
            data_inicial.set(Calendar.MINUTE, 0);
            data_inicial.set(Calendar.HOUR_OF_DAY, 0);

            data_final.set(Calendar.MILLISECOND, 0);
            data_final.set(Calendar.SECOND, 0);
            data_final.set(Calendar.MINUTE, 0);
            data_final.set(Calendar.HOUR_OF_DAY, 0);
            Long tempo = ((data_final.getTimeInMillis() - data_inicial.getTimeInMillis()) / MILLIS_IN_DAY);
            
            dias += tempo.intValue();     
            
            System.out.println(dias);
            if(!TextDInicial.getText().matches("[a-zA-Z]+") && !TextDFinal.getText().matches("[a-zA-Z]+")){
                if(TextDInicial.getText().length()==10 && TextDFinal.getText().length()==10){
                    if(dias>0){                   
                        TextPrecoTotal.setText("" + Integer.parseInt(TextPreco.getText()) * dias);
                        return;
                    }
                }
            }
            
            TextPrecoTotal.setText("");
            
        } catch(Exception e){

        }

    }//GEN-LAST:event_TextDInicialKeyTyped

    private void TextDFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDFinalKeyTyped
        dias = 1;
        try{
            Date temp;     
            Calendar data_inicial = Calendar.getInstance();
            Calendar data_final = Calendar.getInstance();
            
            SimpleDateFormat sdftraco = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat sdfbarra = new SimpleDateFormat("dd/MM/yyyy");

            if(TextDInicial.getText().contains("-")){
                temp = sdftraco.parse(TextDInicial.getText());
                Dinicial = temp;
                data_inicial.setTime(temp);
            }else{
                if(TextDInicial.getText().contains("/")){
                    temp = sdfbarra.parse(TextDInicial.getText());
                    Dinicial = temp;
                    data_inicial.setTime(temp);
                }else{
                    return;
                }
            }
            
            if(TextDFinal.getText().contains("-")){
                temp = sdftraco.parse(TextDFinal.getText());
                Dfinal = temp;
                data_final.setTime(temp);
            }else{            
                if(TextDFinal.getText().contains("/")){
                    temp = sdfbarra.parse(TextDFinal.getText());
                    Dfinal = temp;
                    data_inicial.setTime(temp);
                }else{
                    return;
                }
            }
            
            int MILLIS_IN_DAY = 86400000;

            data_inicial.set(Calendar.MILLISECOND, 0);
            data_inicial.set(Calendar.SECOND, 0);
            data_inicial.set(Calendar.MINUTE, 0);
            data_inicial.set(Calendar.HOUR_OF_DAY, 0);

            data_final.set(Calendar.MILLISECOND, 0);
            data_final.set(Calendar.SECOND, 0);
            data_final.set(Calendar.MINUTE, 0);
            data_final.set(Calendar.HOUR_OF_DAY, 0);
            Long tempo = ((data_final.getTimeInMillis() - data_inicial.getTimeInMillis()) / MILLIS_IN_DAY);
            
            dias += tempo.intValue();     
            
            System.out.println(dias);
            if(!TextDInicial.getText().matches("[a-zA-Z]+") && !TextDFinal.getText().matches("[a-zA-Z]+")){
                if(TextDInicial.getText().length()==10 && TextDFinal.getText().length()==10){
                    if(dias>0){                   
                        TextPrecoTotal.setText("" + Integer.parseInt(TextPreco.getText()) * dias);
                        return;
                    }
                }
            }
            
            TextPrecoTotal.setText("");
            
        } catch(Exception e){
            
        }
            
    }//GEN-LAST:event_TextDFinalKeyTyped

    private void TextDInicialInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TextDInicialInputMethodTextChanged
        
    }//GEN-LAST:event_TextDInicialInputMethodTextChanged

    private void TextDFinalInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TextDFinalInputMethodTextChanged
        
    }//GEN-LAST:event_TextDFinalInputMethodTextChanged

    private void TextBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextBuscaKeyTyped
        
    }//GEN-LAST:event_TextBuscaKeyTyped

    private void BtnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcurarActionPerformed
        try{
            
            String op="";
            for (Enumeration<AbstractButton> buttons = BtnGroup.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();
                if (button.isSelected()) {
                        op = button.getText();
                }
            }
            if(op.equals("")){
                return;
            }       

            ArrayList<Carro> carros = new ArrayList();
            if(op.equals("Modelo")){
                CarroController.getCarrosPorX(carros,"modelo",TextBusca.getText());
            }

            if(op.equals("Fabricante")){
                CarroController.getCarrosPorX(carros,"fabricante",TextBusca.getText());
            }

            if(op.equals("Cor")){
                System.out.println(TextBusca.getText());
                CarroController.getCarrosPorX(carros,"cor",TextBusca.getText());
                System.out.println(carros.get(0));
            }

            if(op.equals("Ano")){
                CarroController.getCarrosPorX(carros,"ano",TextBusca.getText());
            }

            if(op.equals("Preço")){
                CarroController.getCarrosPorX(carros,"aluguel",TextBusca.getText());
            }

            if(TextBusca.getText().equals("")){
                CarroController.getAll(carros);
            }
            
            ArrayList<Carro> aux = CarroController.OrdenaCarros(carros);
             
            this.carros = aux;
            
            System.out.println(this.carros.size());
            
            DefaultListModel model = new DefaultListModel(); 
            this.TextLista.setModel(model);         
            for(int i = 0; i <= this.carros.size(); i++){
                model.addElement(this.carros.get(i).getModelo());
            }
            
        }catch(NullPointerException e){
            
        }catch(IndexOutOfBoundsException e){
            
        }
    }//GEN-LAST:event_BtnProcurarActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alocar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlugar;
    private javax.swing.ButtonGroup BtnGroup;
    private javax.swing.JButton BtnProcurar;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JTextPane TextAno;
    private javax.swing.JTextPane TextBusca;
    private javax.swing.JTextPane TextCor;
    private javax.swing.JTextPane TextDFinal;
    private javax.swing.JTextPane TextDInicial;
    private javax.swing.JTextPane TextFabricante;
    private javax.swing.JList<String> TextLista;
    private javax.swing.JTextPane TextModelo;
    private javax.swing.JTextPane TextPreco;
    private javax.swing.JTextPane TextPrecoTotal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
