package VIEW;

import MODELS.Cliente;
import CONTROLLER.ClienteController;
import static CONTROLLER.ClienteController.getAll;
import java.util.ArrayList;

public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        TextLogin7 = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextLogin = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        TextSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        TextConfSenha = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextNome = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextCpf = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextEmail = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextTelefone = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextDT = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextCep = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TextCidade = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TextNumero = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TextComplemento = new javax.swing.JTextPane();
        BtnCadastrar = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TextRua = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();

        jScrollPane8.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane8ComponentAdded(evt);
            }
        });

        TextLogin7.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextLogin7ComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextLogin7ComponentRemoved(evt);
            }
        });
        jScrollPane8.setViewportView(TextLogin7);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("DT (CNH)");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar-se");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Login");

        jScrollPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane1ComponentAdded(evt);
            }
        });

        TextLogin.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextLoginComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextLoginComponentRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(TextLogin);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Senha");

        TextSenha.setToolTipText("");
        TextSenha.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextSenhaComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextSenhaComponentRemoved(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Confirme a senha");

        TextConfSenha.setToolTipText("");
        TextConfSenha.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextConfSenhaComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextConfSenhaComponentRemoved(evt);
            }
        });

        jScrollPane2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane2ComponentAdded(evt);
            }
        });

        TextNome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextNomeComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextNomeComponentRemoved(evt);
            }
        });
        jScrollPane2.setViewportView(TextNome);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nome");

        jScrollPane3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane3ComponentAdded(evt);
            }
        });

        TextCpf.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextCpfComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextCpfComponentRemoved(evt);
            }
        });
        jScrollPane3.setViewportView(TextCpf);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("CPF");

        jScrollPane4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane4ComponentAdded(evt);
            }
        });

        TextEmail.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextEmailComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextEmailComponentRemoved(evt);
            }
        });
        jScrollPane4.setViewportView(TextEmail);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Email");

        jScrollPane5.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane5ComponentAdded(evt);
            }
        });

        TextTelefone.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextTelefoneComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextTelefoneComponentRemoved(evt);
            }
        });
        jScrollPane5.setViewportView(TextTelefone);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Telefone");

        jScrollPane6.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane6ComponentAdded(evt);
            }
        });

        TextDT.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextDTComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextDTComponentRemoved(evt);
            }
        });
        jScrollPane6.setViewportView(TextDT);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("DT (CNH)");

        jScrollPane7.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane7ComponentAdded(evt);
            }
        });

        TextCep.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextCepComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextCepComponentRemoved(evt);
            }
        });
        jScrollPane7.setViewportView(TextCep);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("CEP");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Cidade");

        jScrollPane9.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane9ComponentAdded(evt);
            }
        });

        TextCidade.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextCidadeComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextCidadeComponentRemoved(evt);
            }
        });
        jScrollPane9.setViewportView(TextCidade);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Número");

        jScrollPane10.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane10ComponentAdded(evt);
            }
        });

        TextNumero.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextNumeroComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextNumeroComponentRemoved(evt);
            }
        });
        jScrollPane10.setViewportView(TextNumero);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Complemento");

        jScrollPane11.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane11ComponentAdded(evt);
            }
        });

        TextComplemento.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextComplementoComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextComplementoComponentRemoved(evt);
            }
        });
        jScrollPane11.setViewportView(TextComplemento);

        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        ErrorLabel.setForeground(new java.awt.Color(251, 0, 0));

        jScrollPane12.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane12ComponentAdded(evt);
            }
        });

        TextRua.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextRuaComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextRuaComponentRemoved(evt);
            }
        });
        jScrollPane12.setViewportView(TextRua);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Rua");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane9)))
                    .addComponent(TextSenha)
                    .addComponent(TextConfSenha)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCadastrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextLoginComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextLoginComponentAdded

    }//GEN-LAST:event_TextLoginComponentAdded

    private void TextLoginComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextLoginComponentRemoved

    }//GEN-LAST:event_TextLoginComponentRemoved

    private void jScrollPane1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1ComponentAdded

    private void TextSenhaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenhaComponentAdded

    }//GEN-LAST:event_TextSenhaComponentAdded

    private void TextSenhaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenhaComponentRemoved

    }//GEN-LAST:event_TextSenhaComponentRemoved

    private void TextConfSenhaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextConfSenhaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextConfSenhaComponentAdded

    private void TextConfSenhaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextConfSenhaComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextConfSenhaComponentRemoved

    private void TextNomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNomeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeComponentAdded

    private void TextNomeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNomeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeComponentRemoved

    private void jScrollPane2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2ComponentAdded

    private void TextCpfComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCpfComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpfComponentAdded

    private void TextCpfComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCpfComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpfComponentRemoved

    private void jScrollPane3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3ComponentAdded

    private void TextEmailComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextEmailComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailComponentAdded

    private void TextEmailComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextEmailComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailComponentRemoved

    private void jScrollPane4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4ComponentAdded

    private void TextTelefoneComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextTelefoneComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneComponentAdded

    private void TextTelefoneComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextTelefoneComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneComponentRemoved

    private void jScrollPane5ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane5ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane5ComponentAdded

    private void TextDTComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextDTComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDTComponentAdded

    private void TextDTComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextDTComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDTComponentRemoved

    private void jScrollPane6ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane6ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane6ComponentAdded

    private void TextCepComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCepComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCepComponentAdded

    private void TextCepComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCepComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCepComponentRemoved

    private void jScrollPane7ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane7ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane7ComponentAdded

    private void TextLogin7ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextLogin7ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLogin7ComponentAdded

    private void TextLogin7ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextLogin7ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLogin7ComponentRemoved

    private void jScrollPane8ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane8ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane8ComponentAdded

    private void TextCidadeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCidadeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCidadeComponentAdded

    private void TextCidadeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCidadeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCidadeComponentRemoved

    private void jScrollPane9ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane9ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane9ComponentAdded

    private void TextNumeroComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNumeroComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumeroComponentAdded

    private void TextNumeroComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNumeroComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumeroComponentRemoved

    private void jScrollPane10ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane10ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane10ComponentAdded

    private void TextComplementoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextComplementoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextComplementoComponentAdded

    private void TextComplementoComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextComplementoComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextComplementoComponentRemoved

    private void jScrollPane11ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane11ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane11ComponentAdded

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed

        //VERIFICAÇÕES
        if(TextLogin.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Login.");
            return;
        }
        
        if(TextLogin.getText().length()<5 || TextLogin.getText().length()>30){
            ErrorLabel.setText("O login deve ter pelo menos 5 caracteres e no máximo 30.");
            return;
        }
        
        ArrayList<Cliente> clientes = new ArrayList();
        ClienteController.getAll(clientes);
        for(int i = 0; i < clientes.size(); i++){
            if(clientes.get(i).getLogin().equals(TextLogin.getText())){
                ErrorLabel.setText("O login já existe!");
                return;
            }
        }        
        //
        if(TextSenha.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Senha.");
            return;
        }
        
        if(TextSenha.getText().length()<8){
            ErrorLabel.setText("A senha deve ter pelo menos 8 caracteres.");
            return;
        }
        //
        if(TextConfSenha.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Confirme a Senha.");
            return;
        }
        
        if(!TextConfSenha.getText().equals(TextSenha.getText())){
            ErrorLabel.setText("As senhas não são iguais.");
            return;
        }
        //
        if(TextNome.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Nome.");
            return;
        }
        
        if(TextNome.getText().length()>50){
            ErrorLabel.setText("O nome é muito longo");
            return;
        }    
        
        if(!TextNome.getText().replace(" ","").matches("[a-zA-Z]+")){
            ErrorLabel.setText("O nome deve possuir somente letras.");
            return;
        }
        //
        if(TextCpf.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de CPF.");
            return;
        }
        
        if(TextCpf.getText().length()!=11){
            ErrorLabel.setText("O CPF deve ter 11 números.");
            return;
        }
        
        if(!TextCpf.getText().matches("[0-9]*")){
            ErrorLabel.setText("O CPF deve possuir somente números.");
            return;
        }
        //
        if(TextEmail.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Email.");
            return;
        }
        
        if(TextEmail.getText().length()>100){
            ErrorLabel.setText("Email muito longo, tente novamente.");
            return;
        }
        
        if(!TextEmail.getText().contains("@") || !TextEmail.getText().contains(".")){
            ErrorLabel.setText("Modelo de Email inválido.");
            return;
        }
        //
        if(TextTelefone.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Telefone.");
            return;
        }
        
        if(TextTelefone.getText().length()>20){
            ErrorLabel.setText("Telefone muito longo, tente novamente.");
            return;
        }
        
        if(TextTelefone.getText().contains("[a-zA-Z]+")){
            ErrorLabel.setText("O Telefone não deve possuir letras.");
            return;
        }
        //
        if(TextDT.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de DT (CNH).");
            return;
        }
        
        if(TextDT.getText().length()!=11){
            ErrorLabel.setText("O DT deve ter 11 números.");
            return;
        }
        
        if(!TextDT.getText().matches("[0-9]*")){
            ErrorLabel.setText("O DT (CNH) deve possuir somente números.");
            return;
        }
        //
        if(TextCep.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de CEP.");
            return;
        }
        
        if(TextCep.getText().length()<8 || TextCep.getText().length()>9){
            ErrorLabel.setText("CEP inválido, tente novamente.");
            return;
        }        
        //
        if(TextCidade.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Cidade.");
            return;
        }
        
        if(TextCidade.getText().length()>40){
            ErrorLabel.setText("Cidade muito longo, tente novamente.");
            return;
        }
        //
        if(TextRua.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Rua.");
            return;
        }
        
        if(TextRua.getText().length()>50){
            ErrorLabel.setText("Rua muito longo, tente novamente.");
            return;
        }
        //
        if(TextNumero.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Numero.");
            return;
        }
        
        if(TextNumero.getText().length()>8){
            ErrorLabel.setText("Número muito longo, tente novamente.");
            return;
        }    
        
        if(!TextNumero.getText().matches("[0-9]*")){
            ErrorLabel.setText("O Número deve possuir somente números.");
            return;
        }
        //
        
        //SE NADA RETORNAR:
        Cliente c = new Cliente();
        c.setLogin(TextLogin.getText());
        c.setCpf(TextCpf.getText());
        c.setSenha(TextSenha.getText());
        c.setNome(TextNome.getText());
        c.setEmail(TextEmail.getText());
        c.setTelefone(TextTelefone.getText());
        c.setDtcadastro(TextDT.getText());
        c.setCep(TextCep.getText());
        c.setCidade(TextCidade.getText());
        c.setRua(TextRua.getText());
        c.setNumero(Integer.parseInt(TextNumero.getText()));
        c.setComplemento(TextComplemento.getText());
        
        ClienteController.cadastrar(c);
        MessageWindow mensagem = new MessageWindow("Cadastro efetuado com sucesso!");
        mensagem.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void TextRuaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextRuaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRuaComponentAdded

    private void TextRuaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextRuaComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRuaComponentRemoved

    private void jScrollPane12ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane12ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane12ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JTextPane TextCep;
    private javax.swing.JTextPane TextCidade;
    private javax.swing.JTextPane TextComplemento;
    private javax.swing.JPasswordField TextConfSenha;
    private javax.swing.JTextPane TextCpf;
    private javax.swing.JTextPane TextDT;
    private javax.swing.JTextPane TextEmail;
    private javax.swing.JTextPane TextLogin;
    private javax.swing.JTextPane TextLogin7;
    private javax.swing.JTextPane TextNome;
    private javax.swing.JTextPane TextNumero;
    private javax.swing.JTextPane TextRua;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextPane TextTelefone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
