package VIEW;

import CONTROLLER.ClienteController;
import MODELS.Cliente;

public class Dados_Pessoais extends javax.swing.JFrame {
    Cliente cliente;

    public Dados_Pessoais(Cliente cliente) {
        this.cliente = cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        TextSenha1 = new javax.swing.JPasswordField();
        TextSenha2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        TextSenha4 = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextLogin = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextNome = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextCpf = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextEmail = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextTelefone = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextDT = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextCep = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TextCidade = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TextNumero = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TextComplemento = new javax.swing.JTextPane();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        BtnTrocar = new javax.swing.JButton();
        TextSenha = new javax.swing.JPasswordField();
        TextAltSenha = new javax.swing.JPasswordField();
        TextAltSenhaConf = new javax.swing.JPasswordField();
        ErrorLabel = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TextRua = new javax.swing.JTextPane();
        jLabel20 = new javax.swing.JLabel();

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Senha");

        TextSenha1.setToolTipText("");
        TextSenha1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextSenha1ComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextSenha1ComponentRemoved(evt);
            }
        });

        TextSenha2.setToolTipText("");
        TextSenha2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextSenha2ComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextSenha2ComponentRemoved(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Senha");

        TextSenha4.setToolTipText("");
        TextSenha4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextSenha4ComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextSenha4ComponentRemoved(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Senha");

        jScrollPane8.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados Pessoais");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Login");

        jScrollPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane1ComponentAdded(evt);
            }
        });

        TextLogin.setEditable(false);
        TextLogin.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextLoginComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextLoginComponentRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(TextLogin);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Senha Atual");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nome");

        jScrollPane2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane2ComponentAdded(evt);
            }
        });

        TextNome.setEditable(false);
        TextNome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextNomeComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextNomeComponentRemoved(evt);
            }
        });
        jScrollPane2.setViewportView(TextNome);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("CPF");

        jScrollPane3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane3ComponentAdded(evt);
            }
        });

        TextCpf.setEditable(false);
        TextCpf.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextCpfComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextCpfComponentRemoved(evt);
            }
        });
        jScrollPane3.setViewportView(TextCpf);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Email");

        jScrollPane4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane4ComponentAdded(evt);
            }
        });

        TextEmail.setEditable(false);
        TextEmail.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextEmailComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextEmailComponentRemoved(evt);
            }
        });
        jScrollPane4.setViewportView(TextEmail);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Telefone");

        jScrollPane5.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane5ComponentAdded(evt);
            }
        });

        TextTelefone.setEditable(false);
        TextTelefone.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextTelefoneComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextTelefoneComponentRemoved(evt);
            }
        });
        jScrollPane5.setViewportView(TextTelefone);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("DT (CNH)");

        jScrollPane6.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane6ComponentAdded(evt);
            }
        });

        TextDT.setEditable(false);
        TextDT.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextDTComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextDTComponentRemoved(evt);
            }
        });
        jScrollPane6.setViewportView(TextDT);

        jScrollPane7.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane7ComponentAdded(evt);
            }
        });

        TextCep.setEditable(false);
        TextCep.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextCepComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextCepComponentRemoved(evt);
            }
        });
        jScrollPane7.setViewportView(TextCep);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("CEP");

        jScrollPane9.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane9ComponentAdded(evt);
            }
        });

        TextCidade.setEditable(false);
        TextCidade.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextCidadeComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextCidadeComponentRemoved(evt);
            }
        });
        jScrollPane9.setViewportView(TextCidade);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Cidade");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Número");

        jScrollPane10.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane10ComponentAdded(evt);
            }
        });

        TextNumero.setEditable(false);
        TextNumero.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextNumeroComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextNumeroComponentRemoved(evt);
            }
        });
        jScrollPane10.setViewportView(TextNumero);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Complemento");

        jScrollPane11.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane11ComponentAdded(evt);
            }
        });

        TextComplemento.setEditable(false);
        TextComplemento.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextComplementoComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextComplementoComponentRemoved(evt);
            }
        });
        jScrollPane11.setViewportView(TextComplemento);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Alterar Senha");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Dados Pessoais");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Nova Senha");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Confirme a Nova Senha");

        BtnTrocar.setText("Trocar");
        BtnTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrocarActionPerformed(evt);
            }
        });

        TextAltSenhaConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAltSenhaConfActionPerformed(evt);
            }
        });

        ErrorLabel.setForeground(new java.awt.Color(251, 0, 0));

        jScrollPane12.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane12ComponentAdded(evt);
            }
        });

        TextRua.setEditable(false);
        TextRua.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TextRuaComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                TextRuaComponentRemoved(evt);
            }
        });
        jScrollPane12.setViewportView(TextRua);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Rua");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTrocar)
                        .addGap(280, 280, 280))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextAltSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextAltSenhaConf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextSenha)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                            .addComponent(jLabel2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextAltSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextAltSenhaConf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTrocar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextLoginComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextLoginComponentAdded

    }//GEN-LAST:event_TextLoginComponentAdded

    private void TextLoginComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextLoginComponentRemoved

    }//GEN-LAST:event_TextLoginComponentRemoved

    private void jScrollPane1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1ComponentAdded

    private void TextNomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNomeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeComponentAdded

    private void TextNomeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNomeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeComponentRemoved

    private void jScrollPane2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2ComponentAdded

    private void TextCpfComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCpfComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpfComponentAdded

    private void TextCpfComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCpfComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpfComponentRemoved

    private void jScrollPane3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3ComponentAdded

    private void TextEmailComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextEmailComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailComponentAdded

    private void TextEmailComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextEmailComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailComponentRemoved

    private void jScrollPane4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4ComponentAdded

    private void TextTelefoneComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextTelefoneComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneComponentAdded

    private void TextTelefoneComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextTelefoneComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneComponentRemoved

    private void jScrollPane5ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane5ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane5ComponentAdded

    private void TextDTComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextDTComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDTComponentAdded

    private void TextDTComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextDTComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDTComponentRemoved

    private void jScrollPane6ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane6ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane6ComponentAdded

    private void TextCepComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCepComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCepComponentAdded

    private void TextCepComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCepComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCepComponentRemoved

    private void jScrollPane7ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane7ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane7ComponentAdded

    private void TextCidadeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCidadeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCidadeComponentAdded

    private void TextCidadeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextCidadeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCidadeComponentRemoved

    private void jScrollPane9ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane9ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane9ComponentAdded

    private void TextNumeroComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNumeroComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumeroComponentAdded

    private void TextNumeroComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextNumeroComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumeroComponentRemoved

    private void jScrollPane10ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane10ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane10ComponentAdded

    private void TextComplementoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextComplementoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextComplementoComponentAdded

    private void TextComplementoComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextComplementoComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextComplementoComponentRemoved

    private void jScrollPane11ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane11ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane11ComponentAdded

    private void TextSenha1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenha1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenha1ComponentAdded

    private void TextSenha1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenha1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenha1ComponentRemoved

    private void TextSenha2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenha2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenha2ComponentAdded

    private void TextSenha2ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenha2ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenha2ComponentRemoved

    private void TextSenha4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenha4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenha4ComponentAdded

    private void TextSenha4ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextSenha4ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenha4ComponentRemoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TextLogin.setText(cliente.getNome());
        TextNome.setText(cliente.getLogin());
        TextCpf.setText(cliente.getCpf());
        TextEmail.setText(cliente.getEmail());
        TextTelefone.setText(cliente.getTelefone());
        TextDT.setText(cliente.getDtcadastro());
        TextCep.setText(cliente.getCep());
        TextCidade.setText(cliente.getCidade());
        TextRua.setText(cliente.getRua());
        TextNumero.setText(""+cliente.getNumero());
        TextComplemento.setText(cliente.getComplemento());
    }//GEN-LAST:event_formWindowOpened

    private void BtnTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrocarActionPerformed
        //VERIFICAÇÕES
        if(TextSenha.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Senha.");
            return;
        }
        
        if(TextSenha.getText().length()<8){
            ErrorLabel.setText("A senha deve ter pelo menos 8 caracteres.");
            return;
        }
        
        if(TextAltSenha.getText().equals("")){
            ErrorLabel.setText("Preencha o campo de Confirme a Senha.");
            return;
        }
        
        if(!TextAltSenha.getText().equals(TextAltSenhaConf.getText())){
            ErrorLabel.setText("As novas senhas não são iguais.");
            return;
        }
        
        if(TextSenha.getText().equals(TextAltSenha.getText())){
            ErrorLabel.setText("A nova senha não pode ser igual a antiga.");
            return;
        }
        //
        
        ClienteController.alterarSenha(TextAltSenha.getText(), cliente.getId());
        ErrorLabel.setText("");
        MessageWindow mensagem = new MessageWindow("Senha alterada com sucesso!");
        mensagem.setVisible(true);
        
    }//GEN-LAST:event_BtnTrocarActionPerformed

    private void TextAltSenhaConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAltSenhaConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAltSenhaConfActionPerformed

    private void TextRuaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextRuaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRuaComponentAdded

    private void TextRuaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TextRuaComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRuaComponentRemoved

    private void jScrollPane12ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane12ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane12ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados_Pessoais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados_Pessoais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados_Pessoais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados_Pessoais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTrocar;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JPasswordField TextAltSenha;
    private javax.swing.JPasswordField TextAltSenhaConf;
    private javax.swing.JTextPane TextCep;
    private javax.swing.JTextPane TextCidade;
    private javax.swing.JTextPane TextComplemento;
    private javax.swing.JTextPane TextCpf;
    private javax.swing.JTextPane TextDT;
    private javax.swing.JTextPane TextEmail;
    private javax.swing.JTextPane TextLogin;
    private javax.swing.JTextPane TextNome;
    private javax.swing.JTextPane TextNumero;
    private javax.swing.JTextPane TextRua;
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JPasswordField TextSenha1;
    private javax.swing.JPasswordField TextSenha2;
    private javax.swing.JPasswordField TextSenha4;
    private javax.swing.JTextPane TextTelefone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
